version: 2.1

workflows:
  spoon-deploy:
    jobs:
    - spoon

jobs:
  spoon:
    docker:
      - image: cimg/go:1.22.0
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: go mod tidy
      - run: 
          name: Run Test
          command: go test ./handler
